PythonProject/PythonProject/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url
from django.views.static import serve #需要导入
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^media/(?P<path>.*)$', serve, {'document_root':settings.MEDIA_ROOT}),#这部分很重要
    url(r'^UserInfo/', include('apps.UserInfo.urls', namespace='UserInfo')),  # 用户模块
    url(r'^PlaceType/', include('apps.PlaceType.urls', namespace='PlaceType')),  # 会议室类型模块
    url(r'^Place/', include('apps.Place.urls', namespace='Place')),  # 会议室模块
    url(r'^OrderInfo/', include('apps.OrderInfo.urls', namespace='OrderInfo')),  # 预约订单模块
    url(r'^PayWay/', include('apps.PayWay.urls', namespace='PayWay')),  # 支付方式模块
    url(r'^TimeInterval/', include('apps.TimeInterval.urls', namespace='TimeInterval')),  # 时段模块
    url(r'^Leaveword/', include('apps.Leaveword.urls', namespace='Leaveword')),  # 留言模块
    url(r'^Notice/', include('apps.Notice.urls', namespace='Notice')),  # 新闻公告模块

    url(r'^', include("apps.Index.urls", namespace="Index")),  # 首页模块

    url(r'^tinymce/', include('tinymce.urls')),
]

PythonProject/apps/Index/urls.py
from django.conf.urls import url
from apps.Index.views import IndexView,FrontLoginView,FrontLoginOutView,LoginView,LoginOutView,MainView,ChangePasswordView

# 正在部署的应用的名称
app_name = 'Index'

urlpatterns = [
    url(r'^$', IndexView.as_view(), name='index'),  # 首页
    url(r'^frontLogin$', FrontLoginView.as_view(), name='frontLogin'),  # 前台登录
    url(r'^frontLoginout$', FrontLoginOutView.as_view(), name='frontLoginout'),  # 前台退出
    url(r'^login$', LoginView.as_view(), name="login"),  # 后台登录
    url(r'^loginout$', LoginOutView.as_view(), name="loginout"),  # 后台退出
    url(r'^main$', MainView.as_view(), name='main'),  # 后台主页面
    url(r'^changePassword$', ChangePasswordView.as_view(), name='changePassword')  # 管理员修改密码
]

PythonProject/apps/TimeInterval/urls.py
from apps.TimeInterval.views import FrontAddView, FrontListView, UpdateView, DeletesView, FrontShowView, AddView, \
    ListView, OutToExcelView, BackModifyView, FrontModifyView, ListAllView
from django.conf.urls import url

# 正在部署的应用的名称
app_name = 'TimeInterval'

urlpatterns = [
    url(r'^frontAdd$', FrontAddView.as_view(), name='frontAdd'),  # 前台添加
    url(r'^frontModify/(?P<intervalId>.+)$', FrontModifyView.as_view(), name='frontModify'),  # 前台更新
    url(r'^frontList$', FrontListView.as_view(), name='frontList'),  # 前台查询列表
    url(r'^frontShow/(?P<intervalId>.+)$', FrontShowView.as_view(), name='frontShow'),  # 前台显示详情页
    url(r'^listAll', ListAllView.as_view(), name='listAll'),  # 前台查询所有信息

    url(r'^update/(?P<intervalId>.+)$', UpdateView.as_view(), name='update'),  # Ajax方式更新记录

    url(r'^add$', AddView.as_view(), name='add'),  # 后台添加
    url(r'^backModify/(?P<intervalId>.+)$', BackModifyView.as_view(), name="backModify"),  # 后台更新
    url(r'^list$', ListView.as_view(), name='list'),  # 后台信息列表
    url(r'^deletes$', DeletesView.as_view(), name="deletes"),  # 删除记录信息
    url(r'^OutToExcel$', OutToExcelView.as_view(), name='OutToExcel')  # 导出信息到excel并下载
]

PythonProject/apps/TimeInterval/models.py
from django.db import models


class TimeInterval(models.Model):
    intervalId = models.AutoField(primary_key=True, verbose_name='时段id')
    intervalName = models.CharField(max_length=20, default='', verbose_name='时段名称')
    product = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='商品数量')

    class Meta:
        db_table = 't_TimeInterval'
        verbose_name = '时段信息'
        verbose_name_plural = verbose_name

    def getJsonObj(self):
        timeInterval = {
            'intervalId': self.intervalId,
            'intervalName': self.intervalName,
            'product': self.product,
        }
        return timeInterval


PythonProject/apps/TimeInterval/views.py
from django.views.generic import View
from apps.BaseView import BaseView
from django.shortcuts import render
from django.core.paginator import Paginator
from apps.TimeInterval.models import TimeInterval
from django.http import JsonResponse
from django.http import FileResponse
from apps.BaseView import ImageFormatException
from django.conf import settings
import pandas as pd
import os


class FrontAddView(BaseView):  # 前台时段添加
    def get(self,request):

        # 使用模板
        return render(request, 'TimeInterval/timeInterval_frontAdd.html')

    def post(self, request):
        timeInterval = TimeInterval() # 新建一个时段对象然后获取参数
        timeInterval.intervalName = request.POST.get('timeInterval.intervalName')
        timeInterval.product = float(request.POST.get('timeInterval.product'))
        timeInterval.save() # 保存时段信息到数据库
        return JsonResponse({'success': True, 'message': '保存成功'})


class FrontModifyView(BaseView):  # 前台修改时段
    def get(self, request, intervalId):
        context = {'intervalId': intervalId}
        return render(request, 'TimeInterval/timeInterval_frontModify.html', context)


class FrontListView(BaseView):  # 前台时段查询列表
    def get(self, request):
        return self.handle(request)

    def post(self, request):
        return self.handle(request)

    def handle(self, request):
        self.getCurrentPage(request)  # 获取当前要显示第几页
        # 下面获取查询参数
        # 然后条件组合查询过滤
        timeIntervals = TimeInterval.objects.all()
        # 对查询结果利用Paginator进行分页
        self.paginator = Paginator(timeIntervals, self.pageSize)
        # 计算总的页码数，要显示的页码列表，总记录等
        self.calculatePages()
        # 获取第page页的Page实例对象
        timeIntervals_page = self.paginator.page(self.currentPage)

        # 构造模板需要的参数
        context = {
            'timeIntervals_page': timeIntervals_page,
            'currentPage': self.currentPage,
            'totalPage': self.totalPage,
            'recordNumber': self.recordNumber,
            'startIndex': self.startIndex,
            'pageList': self.pageList,
        }
        # 渲染模板界面
        return render(request, 'TimeInterval/timeInterval_frontquery_result.html', context)


class FrontShowView(View):  # 前台显示时段详情页
    def get(self, request, intervalId):
        # 查询需要显示的时段对象
        timeInterval = TimeInterval.objects.get(intervalId=intervalId)
        context = {
            'timeInterval': timeInterval
        }
        # 渲染模板显示
        return render(request, 'TimeInterval/timeInterval_frontshow.html', context)


class ListAllView(View): # 前台查询所有时段
    def get(self,request):
        timeIntervals = TimeInterval.objects.all()
        timeIntervalList = []
        for timeInterval in timeIntervals:
            timeIntervalObj = {
                'intervalId': timeInterval.intervalId,
                'intervalName': timeInterval.intervalName,
            }
            timeIntervalList.append(timeIntervalObj)
        return JsonResponse(timeIntervalList, safe=False)


class UpdateView(BaseView):  # Ajax方式时段更新
    def get(self, request, intervalId):
        # GET方式请求查询时段对象并返回时段json格式
        timeInterval = TimeInterval.objects.get(intervalId=intervalId)
        return JsonResponse(timeInterval.getJsonObj())

    def post(self, request, intervalId):
        # POST方式提交时段修改信息更新到数据库
        timeInterval = TimeInterval.objects.get(intervalId=intervalId)
        timeInterval.intervalName = request.POST.get('timeInterval.intervalName')
        timeInterval.product = float(request.POST.get('timeInterval.product'))
        timeInterval.save()
        return JsonResponse({'success': True, 'message': '保存成功'})

class AddView(BaseView):  # 后台时段添加
    def get(self,request):

        # 渲染显示模板界面
        return render(request, 'TimeInterval/timeInterval_add.html')

    def post(self, request):
        # POST方式处理图书添加业务
        timeInterval = TimeInterval() # 新建一个时段对象然后获取参数
        timeInterval.intervalName = request.POST.get('timeInterval.intervalName')
        timeInterval.product = float(request.POST.get('timeInterval.product'))
        timeInterval.save() # 保存时段信息到数据库
        return JsonResponse({'success': True, 'message': '保存成功'})


class BackModifyView(BaseView):  # 后台更新时段
    def get(self, request, intervalId):
        context = {'intervalId': intervalId}
        return render(request, 'TimeInterval/timeInterval_modify.html', context)


class ListView(BaseView):  # 后台时段列表
    def get(self, request):
        # 使用模板
        return render(request, 'TimeInterval/timeInterval_query_result.html')

    def post(self, request):
        # 获取当前要显示第几页和每页几条数据
        self.getPageAndSize(request)
        # 收集查询参数
        # 然后条件组合查询过滤
        timeIntervals = TimeInterval.objects.all()
        # 利用Paginator对查询结果集分页
        self.paginator = Paginator(timeIntervals, self.pageSize)
        # 计算总的页码数，要显示的页码列表，总记录等
        self.calculatePages()
        # 获取第page页的Page实例对象
        timeIntervals_page = self.paginator.page(self.currentPage)
        # 查询的结果集转换为列表
        timeIntervalList = []
        for timeInterval in timeIntervals_page:
            timeInterval = timeInterval.getJsonObj()
            timeIntervalList.append(timeInterval)
        # 构造模板页面需要的参数
        timeInterval_res = {
            'rows': timeIntervalList,
            'total': self.recordNumber,
        }
        # 渲染模板页面显示
        return JsonResponse(timeInterval_res, json_dumps_params={'ensure_ascii':False})

class DeletesView(BaseView):  # 删除时段信息
    def get(self, request):
        return self.handle(request)

    def post(self, request):
        return self.handle(request)

    def handle(self, request):
        intervalIds = self.getStrParam(request, 'intervalIds')
        intervalIds = intervalIds.split(',')
        count = 0
        try:
            for intervalId in intervalIds:
                TimeInterval.objects.get(intervalId=intervalId).delete()
                count = count + 1
            message = '%s条记录删除成功！' % count
            success = True
        except Exception as e:
            message = '数据库外键约束删除失败！'
            success = False
        return JsonResponse({'success': success, 'message': message})


class OutToExcelView(BaseView):  # 导出时段信息到excel并下载
    def get(self, request):
        # 收集查询参数
        # 然后条件组合查询过滤
        timeIntervals = TimeInterval.objects.all()
        #将查询结果集转换成列表
        timeIntervalList = []
        for timeInterval in timeIntervals:
            timeInterval = timeInterval.getJsonObj()
            timeIntervalList.append(timeInterval)
        # 利用pandas实现数据的导出功能
        pf = pd.DataFrame(timeIntervalList)
        # 设置要导入到excel的列
        columns_map = {
            'intervalId': '时段id',
            'intervalName': '时段名称',
            'product': '商品数量',
        }
        pf = pf[columns_map.keys()]
        pf.rename(columns=columns_map, inplace=True)
        # 将空的单元格替换为空字符
        pf.fillna('', inplace=True)
        #设定文件名和导出路径
        filename = 'timeIntervals.xlsx'
        # 这个路径可以在settings中设置也可以直接手动输入
        root_path = settings.MEDIA_ROOT + '/output/'
        file_path = os.path.join(root_path, filename)
        pf.to_excel(file_path, encoding='utf-8', index=False)
        # 将生成的excel文件输出到网页下载
        file = open(file_path, 'rb')
        response = FileResponse(file)
        response['Content-Type'] = 'application/octet-stream'
        response['Content-Disposition'] = 'attachment;filename="timeIntervals.xlsx"'
        return response


PythonProject/templates/TimeInterval/timeInterval_add.html
{% include 'check_logstate.html' %}
{% load staticfiles %}

 <link rel="stylesheet" type="text/css" href="{% static 'css/timeInterval.css' %}" />
<div id="timeIntervalAddDiv">
    {% csrf_token %}
	<form id="timeIntervalAddForm" enctype="multipart/form-data"  method="post">
		<div>
			<span class="label">时段名称:</span>
			<span class="inputControl">
				<input class="textbox" type="text" id="timeInterval_intervalName" name="timeInterval.intervalName" style="width:200px" />

			</span>

		</div>
		<div>
			<span class="label">商品数量:</span>
			<span class="inputControl">
				<input class="textbox" type="text" id="timeInterval_product" name="timeInterval.product" style="width:80px" />

			</span>

		</div>
		<div class="operation">
			<a id="timeIntervalAddButton" class="easyui-linkbutton">添加</a>
			<a id="timeIntervalClearButton" class="easyui-linkbutton">重填</a>
		</div> 
	</form>
</div>
<script src="{% static 'js/TimeInterval/timeInterval_add.js' %}"></script>

PythonProject/templates/TimeInterval/timeInterval_frontAdd.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1 , user-scalable=no">
<title>时段添加</title>
<link href="{% static 'plugins/bootstrap.css' %}" rel="stylesheet">
<link href="{% static 'plugins/bootstrap-dashen.css' %}" rel="stylesheet">
<link href="{% static 'plugins/font-awesome.css' %}" rel="stylesheet">
<link href="{% static 'plugins/animate.css' %}" rel="stylesheet">
<link href="{% static 'plugins/bootstrap-datetimepicker.min.css' %}" rel="stylesheet" media="screen">
</head>
<body style="margin-top:70px;">
{% include 'header.html' %}
<div class="container">
	<div class="row">
		<div class="col-md-12 wow fadeInUp" data-wow-duration="0.5s">
			<div>
				<!-- Nav tabs -->
				<ul class="nav nav-tabs" role="tablist">
			    	<li role="presentation" ><a href="{% url 'TimeInterval:frontList' %}">时段列表</a></li>
			    	<li role="presentation" class="active"><a href="#timeIntervalAdd" aria-controls="timeIntervalAdd" role="tab" data-toggle="tab">添加时段</a></li>
				</ul>
				<!-- Tab panes -->
				<div class="tab-content">
				    <div role="tabpanel" class="tab-pane" id="timeIntervalList">
				    </div>
				    <div role="tabpanel" class="tab-pane active" id="timeIntervalAdd"> 
				      	<form class="form-horizontal" name="timeIntervalAddForm" id="timeIntervalAddForm" enctype="multipart/form-data" method="post"  class="mar_t15">
				    {% csrf_token %}
						  <div class="form-group">
						  	 <label for="timeInterval_intervalName" class="col-md-2 text-right">时段名称:</label>
						  	 <div class="col-md-8">
							    <input type="text" id="timeInterval_intervalName" name="timeInterval.intervalName" class="form-control" placeholder="请输入时段名称">
							 </div>
						  </div>
						  <div class="form-group">
						  	 <label for="timeInterval_product" class="col-md-2 text-right">商品数量:</label>
						  	 <div class="col-md-8">
							    <input type="text" id="timeInterval_product" name="timeInterval.product" class="form-control" placeholder="请输入商品数量">
							 </div>
						  </div>
				          <div class="form-group">
				             <span class="col-md-2"></span>
				             <span onclick="ajaxTimeIntervalAdd();" class="btn btn-primary bottom5 top5">添加</span>
				          </div>
						</form> 
				        <style>#timeIntervalAddForm .form-group {margin:10px;}  </style>
					</div>
				</div>
			</div>
		</div>
	</div> 
</div>

{% include 'footer.html' %}
<script src="{% static 'plugins/jquery.min.js' %}"></script>
<script src="{% static 'plugins/bootstrap.js' %}"></script>
<script src="{% static 'plugins/wow.min.js' %}"></script>
<script src="{% static 'plugins/bootstrapvalidator/js/bootstrapValidator.min.js' %}"></script>
<script type="text/javascript" src="{% static 'plugins/bootstrap-datetimepicker.min.js' %}" charset="UTF-8"></script>
<script type="text/javascript" src="{% static 'plugins/locales/bootstrap-datetimepicker.zh-CN.js' %}" charset="UTF-8"></script>
<script>
	//提交添加时段信息
	function ajaxTimeIntervalAdd() { 
		//提交之前先验证表单
		$("#timeIntervalAddForm").data('bootstrapValidator').validate();
		if(!$("#timeIntervalAddForm").data('bootstrapValidator').isValid()){
			return;
		}
		jQuery.ajax({
			type : "post",
			url : "{% url 'TimeInterval:frontAdd' %}",
			dataType : "json" , 
			data: new FormData($("#timeIntervalAddForm")[0]),
			success : function(obj) {
				if(obj.success){ 
					alert("保存成功！");
					location.reload();
				} else {
					alert(obj.message);
				}
			},
			processData: false, 
			contentType: false, 
		});
	} 
$(function(){
	/*小屏幕导航点击关闭菜单*/
    $('.navbar-collapse a').click(function(){
        $('.navbar-collapse').collapse('hide');
    });
    new WOW().init();
	//验证时段添加表单字段
	$('#timeIntervalAddForm').bootstrapValidator({
		feedbackIcons: {
			valid: 'glyphicon glyphicon-ok',
			invalid: 'glyphicon glyphicon-remove',
			validating: 'glyphicon glyphicon-refresh'
		},
		fields: {
			"timeInterval.intervalName": {
				validators: {
					notEmpty: {
						message: "时段名称不能为空",
					}
				}
			},
			"timeInterval.product": {
				validators: {
					notEmpty: {
						message: "商品数量不能为空",
					},
					numeric: {
						message: "商品数量不正确"
					}
				}
			},
		}
	}); 
})
</script>
</body>
</html>

PythonProject/templates/TimeInterval/timeInterval_frontquery_result.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1 , user-scalable=no">
<title>时段查询</title>
<link href="{% static 'plugins/bootstrap.css' %}" rel="stylesheet">
<link href="{% static 'plugins/bootstrap-dashen.css' %}" rel="stylesheet">
<link href="{% static 'plugins/font-awesome.css' %}" rel="stylesheet">
<link href="{% static 'plugins/animate.css' %}" rel="stylesheet">
<link href="{% static 'plugins/bootstrap-datetimepicker.min.css' %}" rel="stylesheet" media="screen">
</head>
<body style="margin-top:70px;">
<div class="container">
{% include 'header.html' %}
	<div class="row"> 
	<div style="display:none;">
		<div class="page-header">
    		<h1>时段查询</h1>
		</div>
		<form name="timeIntervalQueryForm" id="timeIntervalQueryForm" action="{% url 'TimeInterval:frontList' %}" class="mar_t15" method="post">
			 {% csrf_token %}
            <input type=hidden name=currentPage value="{{ currentPage }}" />
            <button type="submit" class="btn btn-primary">查询</button>
        </form>
	</div>

		<div class="col-md-12 wow fadeInDown" data-wow-duration="0.5s">
			<div>
				<!-- Nav tabs -->
				<ul class="nav nav-tabs" role="tablist">
			    	<li><a href="{% url 'Index:index' %}">首页</a></li>
			    	<li role="presentation" class="active"><a href="#timeIntervalListPanel" aria-controls="timeIntervalListPanel" role="tab" data-toggle="tab">时段列表</a></li>
			    	<li role="presentation" ><a href="{% url 'TimeInterval:frontAdd' %}" style="display:none;">添加时段</a></li>
				</ul>
			  	<!-- Tab panes -->
			  	<div class="tab-content">
				    <div role="tabpanel" class="tab-pane active" id="timeIntervalListPanel">
				    		<div class="row">
				    			<div class="col-md-12 top5">
				    				<div class="table-responsive">
				    				<table class="table table-condensed table-hover">
				    					<tr class="success bold"><td>序号</td><td>时段id</td><td>时段名称</td><td>商品数量</td><td>操作</td></tr>
                                        {% for timeInterval in timeIntervals_page %}
 										<tr>
 											<td>{{ startIndex|add:forloop.counter }}</td>
 											<td>{{ timeInterval.intervalId }}</td>
 											<td>{{ timeInterval.intervalName }}</td>
 											<td>{{ timeInterval.product }}</td>
 											<td>
 												<a href="{% url 'TimeInterval:frontShow' timeInterval.intervalId  %}"><i class="fa fa-info"></i>&nbsp;查看</a>&nbsp;
 												<a href="#" onclick="timeIntervalEdit('{{ timeInterval.intervalId }}');" style="display:none;"><i class="fa fa-pencil fa-fw"></i>编辑</a>&nbsp;
 												<a href="#" onclick="timeIntervalDelete('{{ timeInterval.intervalId }}');" style="display:none;"><i class="fa fa-trash-o fa-fw"></i>删除</a>
 											</td> 
 										</tr>
 										{% endfor %}
				    				</table>
				    				</div>
				    			</div>
				    		</div>

				    		<div class="row">
					            <div class="col-md-12">
						            <nav class="pull-left">
						                <ul class="pagination">
						                    <li><a href="#" onclick="GoToPage({{ currentPage|add:-1 }},{{ totalPage }}>);" aria-label="Previous"><span aria-hidden="true">&laquo;</span></a></li>
                                            {% for page in pageList %}
                                            {% if currentPage == page %}
						                        <li class="active"><a href="#"  onclick="GoToPage({{ page }},{{ totalPage }});">{{ page }}</a></li>
						                    {% else %}
                                                <li><a href="#"  onclick="GoToPage({{ page }},{{ totalPage }});">{{ page }}</a></li>
                                            {% endif %}
                                            {% endfor %}
						                    <li><a href="#" onclick="GoToPage({{ currentPage|add:1 }},{{ totalPage }});"><span aria-hidden="true">&raquo;</span></a></li>
						                </ul>
						            </nav>
						            <div class="pull-right" style="line-height:75px;" >共有{{ recordNumber }}条记录，当前第{{ currentPage }}/{{ totalPage }} 页</div>
					            </div>
				            </div> 
				    </div>
				</div>
			</div>
		</div>
		</div>
	</div> 
<div id="timeIntervalEditDialog" class="modal fade" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title"><i class="fa fa-edit"></i>&nbsp;时段信息编辑</h4>
      </div>
      <div class="modal-body" style="height:450px; overflow: scroll;">
      	<form class="form-horizontal" name="timeIntervalEditForm" id="timeIntervalEditForm" enctype="multipart/form-data" method="post"  class="mar_t15">
		    {% csrf_token %}
		  <div class="form-group">
			 <label for="timeInterval_intervalId_edit" class="col-md-3 text-right">时段id:</label>
			 <div class="col-md-9"> 
			 	<input type="text" id="timeInterval_intervalId_edit" name="timeInterval.intervalId" class="form-control" placeholder="请输入时段id" readOnly>
			 </div>
		  </div> 
		  <div class="form-group">
		  	 <label for="timeInterval_intervalName_edit" class="col-md-3 text-right">时段名称:</label>
		  	 <div class="col-md-9">
			    <input type="text" id="timeInterval_intervalName_edit" name="timeInterval.intervalName" class="form-control" placeholder="请输入时段名称">
			 </div>
		  </div>
		  <div class="form-group">
		  	 <label for="timeInterval_product_edit" class="col-md-3 text-right">商品数量:</label>
		  	 <div class="col-md-9">
			    <input type="text" id="timeInterval_product_edit" name="timeInterval.product" class="form-control" placeholder="请输入商品数量">
			 </div>
		  </div>
		</form> 
	    <style>#timeIntervalEditForm .form-group {margin-bottom:5px;}  </style>
      </div>
      <div class="modal-footer"> 
      	<button type="button" class="btn btn-default" data-dismiss="modal">关闭</button>
      	<button type="button" class="btn btn-primary" onclick="ajaxTimeIntervalModify();">提交</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
{% include 'footer.html' %}
<script src="{% static 'plugins/jquery.min.js' %}"></script>
<script src="{% static 'plugins/bootstrap.js' %}"></script>
<script src="{% static 'plugins/wow.min.js' %}"></script>
<script src="{% static 'plugins/bootstrap-datetimepicker.min.js' %}"></script>
<script src="{% static 'plugins/locales/bootstrap-datetimepicker.zh-CN.js' %}"></script>
<script type="text/javascript" src="{% static 'js/jsdate.js' %}"></script>
<script>
/*跳转到查询结果的某页*/
function GoToPage(currentPage,totalPage) {
    if(currentPage==0) return;
    if(currentPage>totalPage) return;
    document.timeIntervalQueryForm.currentPage.value = currentPage;
    document.timeIntervalQueryForm.submit();
}

/*可以直接跳转到某页*/
function changepage(totalPage)
{
    var pageValue=document.timeIntervalQueryForm.pageValue.value;
    if(pageValue>totalPage) {
        alert('你输入的页码超出了总页数!');
        return ;
    }
    document.timeIntervalQueryForm.currentPage.value = pageValue;
    documenttimeIntervalQueryForm.submit();
}

/*弹出修改时段界面并初始化数据*/
function timeIntervalEdit(intervalId) {
	$.ajax({
		url :  '/TimeInterval/update/' + intervalId,
		type : "get",
		dataType: "json",
		success : function (timeInterval, response, status) {
			if (timeInterval) {
				$("#timeInterval_intervalId_edit").val(timeInterval.intervalId);
				$("#timeInterval_intervalName_edit").val(timeInterval.intervalName);
				$("#timeInterval_product_edit").val(timeInterval.product);
				$('#timeIntervalEditDialog').modal('show');
			} else {
				alert("获取信息失败！");
			}
		}
	});
}

/*删除时段信息*/
function timeIntervalDelete(intervalId) {
    var csrf = $('input[name="csrfmiddlewaretoken"]').val();
	if(confirm("确认删除这个记录")) {
		$.ajax({
			type : "POST",
			url : "/TimeInterval/deletes",
			data : {
				intervalIds : intervalId,
                "csrfmiddlewaretoken": csrf
			},
			success : function (obj) {
				if (obj.success) {
					alert("删除成功");
					$("#timeIntervalQueryForm").submit();
					//location.href= basePath + "TimeInterval/frontlist";
				}
				else 
					alert(obj.message);
			},
		});
	}
}

/*ajax方式提交时段信息表单给服务器端修改*/
function ajaxTimeIntervalModify() {
	$.ajax({
		url :   '/TimeInterval/update/' + $("#timeInterval_intervalId_edit").val(),
		type : "post",
		dataType: "json",
		data: new FormData($("#timeIntervalEditForm")[0]),
		success : function (obj, response, status) {
            if(obj.success){
                alert("信息修改成功！");
                location.href= basePath + "TimeInterval/frontlist";
            }else{
                alert(obj.message);
            } 
		},
		processData: false,
		contentType: false,
	});
}

$(function(){
	/*小屏幕导航点击关闭菜单*/
    $('.navbar-collapse a').click(function(){
        $('.navbar-collapse').collapse('hide');
    });
    new WOW().init();

})
</script>
</body>
</html>
